// Copyright 2021 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
apply from: "$rootDir/gradle/common.gradle"

// Primary dependencies definition
dependencies {
    implementation(project(":gestalt-util"))
    implementation(project(":gestalt-module"))
    implementation(project(":gestalt-inject"))
    annotationProcessor(project(":gestalt-inject-java"))

    implementation(libs.guava)
    implementation(libs.slf4j.api)
    implementation(libs.android.annotation)
    api(libs.jcip)

    testAnnotationProcessor(project(":gestalt-inject-java"))
    testImplementation(libs.junit)
    testImplementation(libs.logback)
    testImplementation(libs.mockito)
}

compileJava {
    inputs.files sourceSets.main.resources.srcDirs
    options.compilerArgs = ["-Aresource=${sourceSets.main.resources.srcDirs.join(File.pathSeparator)}"]
}
compileTestJava {
    inputs.files sourceSets.test.resources.srcDirs
    options.compilerArgs = ["-Aresource=${sourceSets.test.resources.srcDirs.join(File.pathSeparator)}"]
}
