// Copyright 2021 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
apply from: "$rootDir/gradle/common.gradle"

// Primary dependencies definition
dependencies {
    implementation(project(":gestalt-util"))
    implementation(project(":gestalt-module"))
    implementation(project(":gestalt-asset-core"))
    implementation(project(":gestalt-entity-system"))

    implementation(libs.guava)
    implementation(libs.slf4j.api)
    implementation(libs.android.annotation)
    implementation(libs.jcip)

    testImplementation(libs.junit)
    testImplementation(libs.logback)
    testImplementation(libs.mockito)
}

description = "High performance access methods to replace the use of reflections in gestalt-entity-system. Can be used in Java 7+ and Android API 26+."

/***
 * Testpack inclusion
 */

task gatherJarModules(dependsOn: [':testpack:moduleF:jar'], type: Copy)
task gatherModules(dependsOn: [':gestalt-es-perf:gatherJarModules'])

gatherJarModules {
    from '../testpack/moduleF/build/libs/'
    into 'test-modules'
    include('*.jar')
}

test.dependsOn gatherModules
